app-template:
  global:
    fullnameOverride: oid4vc-client-ng
    namespaceOverride: datev-wallet
    labels:
      app: oid4vc-client-ng
  defaultPodOptions:
    imagePullSecrets:
    - name: ghcr-pull-secret
  controllers:
    oid4vc-client-ng:
      type: deployment
      replicas: 1
      containers:
        main:
          nameOverride: oid4vc-client-ng-app
          image:
            repository: ghcr.io/adorsys-gis/oid4vc-client-ng-fe
            tag: "1.0.1"
            pullPolicy: IfNotPresent
          env:
          - name: KEYCLOAK_URL
            value: 'https://keycloak.eudi-adorsys.com'
          - name: KEYCLOAK_REALM
            value: 'oid4vc-vci'
          - name: KEYCLOAK_CLIENT_ID
            value: 'oid4vc-demo-public'
          - name: OID4VC_DEFAULT_CREDENTIAL_CONFIGURATION_ID
            value: 'KMACredential'
          - name: PRODUCTION
            value: 'true'
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
  service:
    app:
      enabled: true
      type: ClusterIP
      controller: oid4vc-client-ng
      ports:
        http:
          enabled: true
          port: 8081
          protocol: HTTP
          targetPort: 8080
  ingress:
    app:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/hostname: oid4vc-client.eudi-adorsys.com
      hosts:
      - host: oid4vc-client.eudi-adorsys.com
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: app
            port: 8081
      tls:
      - secretName: eudi-adorsys-tls
        hosts:
        - "*.eudi-adorsys.com"
        - "eudi-adorsys.com"
