FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_KEYCLOAK_URL=https://keycloak-demo.solutions.adorsys.com
ARG VITE_KEYCLOAK_REALM=oid4vc-vci
ARG VITE_KEYCLOAK_CLIENT_ID=oid4vc-demo-public
ARG VITE_OID4VC_DEFAULT_CREDENTIAL_CONFIGURATION_ID=DatevCompanyCredential
ARG VITE_OID4VC_PRE_AUTHORIZED=false

ENV VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL
ENV VITE_KEYCLOAK_REALM=$VITE_KEYCLOAK_REALM
ENV VITE_KEYCLOAK_CLIENT_ID=$VITE_KEYCLOAK_CLIENT_ID
ENV VITE_OID4VC_DEFAULT_CREDENTIAL_CONFIGURATION_ID=$VITE_OID4VC_DEFAULT_CREDENTIAL_CONFIGURATION_ID
ENV VITE_OID4VC_PRE_AUTHORIZED=$VITE_OID4VC_PRE_AUTHORIZED

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080
